# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `mustermann-grape` gem.
# Please instead update this file by running `bin/tapioca gem mustermann-grape`.


# source://mustermann-grape//lib/mustermann/grape.rb#6
module Mustermann
  class << self
    # source://mustermann/3.0.3/lib/mustermann.rb#89
    def [](name); end

    # source://mustermann/3.0.3/lib/mustermann.rb#120
    def extend_object(object); end

    # source://mustermann/3.0.3/lib/mustermann.rb#62
    def new(*input, type: T.unsafe(nil), operator: T.unsafe(nil), **options); end

    # source://mustermann/3.0.3/lib/mustermann.rb#115
    def normalized_type(type); end

    # source://mustermann/3.0.3/lib/mustermann.rb#110
    def register(name, type); end

    # source://mustermann/3.0.3/lib/mustermann.rb#101
    def try_require(path); end
  end
end

# Grape style pattern implementation.
#
# @example
#   Mustermann.new('/:foo', type: :grape) === '/bar' # => true
# @see Mustermann::Pattern
# @see file:README.md#grape Syntax description in the README
#
# source://mustermann-grape//lib/mustermann/grape.rb#14
class Mustermann::Grape < ::Mustermann::AST::Pattern; end

# source://mustermann-grape//lib/mustermann/grape.rb#0
class Mustermann::Grape::Parser < ::Mustermann::AST::Parser; end
