# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `mustermann` gem.
# Please instead update this file by running `bin/tapioca gem mustermann`.


# Namespace and main entry point for the Mustermann library.
#
# Under normal circumstances the only external API entry point you should be using is {Mustermann.new}.
#
# pkg:gem/mustermann#lib/mustermann/error.rb:2
module Mustermann
  class << self
    # Maps a type to its factory.
    #
    # @example
    #   Mustermann[:sinatra] # => Mustermann::Sinatra
    # @param name [Symbol] a pattern type identifier
    # @raise [ArgumentError] if the type is not supported
    # @return [Class, #new] pattern factory
    #
    # pkg:gem/mustermann#lib/mustermann.rb:89
    def [](name); end

    # pkg:gem/mustermann#lib/mustermann.rb:120
    def extend_object(object); end

    # Creates a new pattern based on input.
    #
    # * From {Mustermann::Pattern}: returns given pattern.
    # * From String: creates a pattern from the string, depending on type option (defaults to {Mustermann::Sinatra})
    # * From Regexp: creates a {Mustermann::Regular} pattern.
    # * From Symbol: creates a {Mustermann::Sinatra} pattern with a single named capture named after the input.
    # * From an Array or multiple inputs: creates a new pattern from each element, combines them to a {Mustermann::Composite}.
    # * From anything else: Will try to call to_pattern on it or raise a TypeError.
    #
    # Note that if the input is a {Mustermann::Pattern}, Regexp or Symbol, the type option is ignored and if to_pattern is
    # called on the object, the type will be handed on but might be ignored by the input object.
    #
    # If you want to enforce the pattern type, you should create them via their expected class.
    #
    # @example creating patterns
    #   require 'mustermann'
    #
    #   Mustermann.new("/:name")                    # => #<Mustermann::Sinatra:"/example">
    #   Mustermann.new("/{name}", type: :template)  # => #<Mustermann::Template:"/{name}">
    #   Mustermann.new(/.*/)                        # => #<Mustermann::Regular:".*">
    #   Mustermann.new(:name, capture: :word)       # => #<Mustermann::Sinatra:":name">
    #   Mustermann.new("/", "/*.jpg", type: :shell) # => #<Mustermann::Composite:(shell:"/" | shell:"/*.jpg")>
    # @example enforcing type
    #   require 'mustermann/sinatra'
    #
    #   Mustermann::Sinatra.new("/:name")
    # @example using custom #to_pattern
    #   require 'mustermann'
    #
    #   class MyObject
    #   def to_pattern(**options)
    #   Mustermann.new("/:name", **options)
    #   end
    #   end
    #
    #   Mustermann.new(MyObject.new, type: :rails) # => #<Mustermann::Rails:"/:name">
    # @param input [String, Pattern, Regexp, Symbol, #to_pattern, Array<String, Pattern, Regexp, Symbol, #to_pattern>] The representation of the pattern
    # @param options [Hash] The options hash
    # @raise [TypeError] if the passed object cannot be converted to a pattern
    # @raise [ArgumentError] if the type is not supported
    # @raise [ArgumentError] if some option is not supported
    # @raise [Mustermann::Error] if the pattern can't be generated from the string
    # @return [Mustermann::Pattern] pattern corresponding to string.
    # @see file:README.md#Types_and_Options "Types and Options" in the README
    #
    # pkg:gem/mustermann#lib/mustermann.rb:62
    def new(*input, type: T.unsafe(nil), operator: T.unsafe(nil), **options); end

    # pkg:gem/mustermann#lib/mustermann.rb:115
    def normalized_type(type); end

    # pkg:gem/mustermann#lib/mustermann.rb:110
    def register(name, type); end

    # @return [LoadError, nil]
    #
    # pkg:gem/mustermann#lib/mustermann.rb:101
    def try_require(path); end
  end
end

# @see Mustermann::AST::Pattern
#
# pkg:gem/mustermann#lib/mustermann/ast/node.rb:3
module Mustermann::AST; end

# Make sure #start and #stop is set on every node and within its parents #start and #stop.
#
# pkg:gem/mustermann#lib/mustermann/ast/boundaries.rb:8
class Mustermann::AST::Boundaries < ::Mustermann::AST::Translator
  # Checks that a node is within the given boundaries.
  #
  # pkg:gem/mustermann#lib/mustermann/ast/boundaries.rb:38
  def set_boundaries(node, start, stop); end

  class << self
    # @return [Mustermann::AST::Node] the ast passed as first argument
    #
    # pkg:gem/mustermann#lib/mustermann/ast/boundaries.rb:11
    def set_boundaries(ast, string: T.unsafe(nil), start: T.unsafe(nil), stop: T.unsafe(nil)); end
  end
end

# pkg:gem/mustermann#lib/mustermann/ast/boundaries.rb:8
class Mustermann::AST::Boundaries::NodeTranslator < ::Mustermann::AST::Translator::NodeTranslator
  class << self
    # pkg:gem/mustermann#lib/mustermann/ast/boundaries.rb:8
    def translator; end
  end
end

# Regexp compilation logic.
#
# pkg:gem/mustermann#lib/mustermann/ast/compiler.rb:9
class Mustermann::AST::Compiler < ::Mustermann::AST::Translator
  # Compiles an AST to a regular expression.
  #
  # @param ast [Mustermann::AST::Node] the tree
  # @return [Regexp] corresponding regular expression.
  #
  # pkg:gem/mustermann#lib/mustermann/ast/compiler.rb:151
  def compile(ast, except: T.unsafe(nil), **options); end

  # @return [String] Regular expression for matching the given character in all representations
  #
  # pkg:gem/mustermann#lib/mustermann/ast/compiler.rb:126
  def encoded(char, uri_decode: T.unsafe(nil), space_matches_plus: T.unsafe(nil), **options); end

  # pkg:gem/mustermann#lib/mustermann/ast/compiler.rb:10
  def error_class; end

  class << self
    # Compiles an AST to a regular expression.
    #
    # @param ast [Mustermann::AST::Node] the tree
    # @return [Regexp] corresponding regular expression.
    #
    # pkg:gem/mustermann#lib/mustermann/ast/compiler.rb:142
    def compile(ast, **options); end
  end
end

# Capture compilation is complex. :(
#
# pkg:gem/mustermann#lib/mustermann/ast/compiler.rb:38
class Mustermann::AST::Compiler::Capture < ::Mustermann::AST::Compiler::NodeTranslator
  # @return [String] regexp without the named capture
  #
  # pkg:gem/mustermann#lib/mustermann/ast/compiler.rb:49
  def pattern(capture: T.unsafe(nil), **options); end

  # pkg:gem/mustermann#lib/mustermann/ast/compiler.rb:42
  def translate(**options); end

  private

  # pkg:gem/mustermann#lib/mustermann/ast/compiler.rb:68
  def default(**options); end

  # pkg:gem/mustermann#lib/mustermann/ast/compiler.rb:64
  def from_array(array, **options); end

  # pkg:gem/mustermann#lib/mustermann/ast/compiler.rb:63
  def from_hash(hash, **options); end

  # pkg:gem/mustermann#lib/mustermann/ast/compiler.rb:67
  def from_nil(**options); end

  # pkg:gem/mustermann#lib/mustermann/ast/compiler.rb:66
  def from_string(string, **options); end

  # pkg:gem/mustermann#lib/mustermann/ast/compiler.rb:65
  def from_symbol(symbol, **options); end

  # pkg:gem/mustermann#lib/mustermann/ast/compiler.rb:61
  def qualified(string, greedy: T.unsafe(nil), **options); end

  # pkg:gem/mustermann#lib/mustermann/ast/compiler.rb:62
  def with_lookahead(string, lookahead: T.unsafe(nil), **options); end
end

# pkg:gem/mustermann#lib/mustermann/ast/compiler.rb:9
class Mustermann::AST::Compiler::NodeTranslator < ::Mustermann::AST::Translator::NodeTranslator
  class << self
    # pkg:gem/mustermann#lib/mustermann/ast/compiler.rb:9
    def translator; end
  end
end

# pkg:gem/mustermann#lib/mustermann/ast/compiler.rb:72
class Mustermann::AST::Compiler::Splat < ::Mustermann::AST::Compiler::Capture
  # splats are always non-greedy
  #
  # pkg:gem/mustermann#lib/mustermann/ast/compiler.rb:76
  def pattern(**options); end
end

# pkg:gem/mustermann#lib/mustermann/ast/compiler.rb:82
class Mustermann::AST::Compiler::Variable < ::Mustermann::AST::Compiler::Capture
  # pkg:gem/mustermann#lib/mustermann/ast/compiler.rb:113
  def default(allow_reserved: T.unsafe(nil), **options); end

  # pkg:gem/mustermann#lib/mustermann/ast/compiler.rb:103
  def parametric(string); end

  # pkg:gem/mustermann#lib/mustermann/ast/compiler.rb:94
  def pattern(parametric: T.unsafe(nil), separator: T.unsafe(nil), **options); end

  # pkg:gem/mustermann#lib/mustermann/ast/compiler.rb:108
  def qualified(string, **options); end

  # pkg:gem/mustermann#lib/mustermann/ast/compiler.rb:118
  def register_param(parametric: T.unsafe(nil), split_params: T.unsafe(nil), separator: T.unsafe(nil), **options); end

  # pkg:gem/mustermann#lib/mustermann/ast/compiler.rb:86
  def translate(**options); end
end

# Looks at an AST, remembers the important bits of information to do an
# ultra fast expansion.
#
# pkg:gem/mustermann#lib/mustermann/ast/expander.rb:12
class Mustermann::AST::Expander < ::Mustermann::AST::Translator
  # add a tree for expansion
  #
  # pkg:gem/mustermann#lib/mustermann/ast/expander.rb:80
  def add(ast); end

  # Creates the product of two of our secret internal data structures.
  #
  # pkg:gem/mustermann#lib/mustermann/ast/expander.rb:141
  def add_to(list, result); end

  # pkg:gem/mustermann#lib/mustermann/ast/expander.rb:13
  def error_class; end

  # helper method for raising an error for unexpandable values
  #
  # @raise [error_class]
  #
  # pkg:gem/mustermann#lib/mustermann/ast/expander.rb:119
  def error_for(values); end

  # @see Mustermann::AST::Translator#expand
  #
  # pkg:gem/mustermann#lib/mustermann/ast/expander.rb:126
  def escape(string, *args, **_arg2); end

  # @see Mustermann::Pattern#expand
  #
  # pkg:gem/mustermann#lib/mustermann/ast/expander.rb:95
  def expand(values); end

  # @return [Boolean]
  # @see Mustermann::Pattern#expandable?
  #
  # pkg:gem/mustermann#lib/mustermann/ast/expander.rb:105
  def expandable?(values); end

  # @see Mustermann::Expander#with_rest
  #
  # pkg:gem/mustermann#lib/mustermann/ast/expander.rb:113
  def expandable_keys(keys); end

  # helper method for captures
  #
  # pkg:gem/mustermann#lib/mustermann/ast/expander.rb:61
  def for_capture(node, **options); end

  # all the known keys
  #
  # pkg:gem/mustermann#lib/mustermann/ast/expander.rb:74
  def keys; end

  # maps sorted key list to sprintf patterns and filters
  #
  # pkg:gem/mustermann#lib/mustermann/ast/expander.rb:68
  def mappings; end

  # Turns a sprintf pattern into our secret internal data structure.
  #
  # pkg:gem/mustermann#lib/mustermann/ast/expander.rb:135
  def pattern(string = T.unsafe(nil), *keys, **filters); end

  # helper method for getting a capture's pattern.
  #
  # pkg:gem/mustermann#lib/mustermann/ast/expander.rb:89
  def pattern_for(node, **options); end
end

# pkg:gem/mustermann#lib/mustermann/ast/expander.rb:12
class Mustermann::AST::Expander::NodeTranslator < ::Mustermann::AST::Translator::NodeTranslator
  class << self
    # pkg:gem/mustermann#lib/mustermann/ast/expander.rb:12
    def translator; end
  end
end

# pkg:gem/mustermann#lib/mustermann/ast/node.rb:5
class Mustermann::AST::Node
  # @return [Node] a new instance of Node
  #
  # pkg:gem/mustermann#lib/mustermann/ast/node.rb:43
  def initialize(payload = T.unsafe(nil), **options); end

  # Loop through all nodes that don't have child nodes.
  #
  # @yield [_self]
  # @yieldparam _self [Mustermann::AST::Node] the object that the method was called on
  #
  # pkg:gem/mustermann#lib/mustermann/ast/node.rb:65
  def each_leaf(&block); end

  # @return [Boolean]
  #
  # pkg:gem/mustermann#lib/mustermann/ast/node.rb:49
  def is_a?(type); end

  # @return [Integer] length of the substring
  #
  # pkg:gem/mustermann#lib/mustermann/ast/node.rb:78
  def length; end

  # @return [Integer] minimum size for a node
  #
  # pkg:gem/mustermann#lib/mustermann/ast/node.rb:84
  def min_size; end

  # Double dispatch helper for reading from the buffer into the payload.
  #
  # pkg:gem/mustermann#lib/mustermann/ast/node.rb:56
  def parse; end

  # Returns the value of attribute payload.
  #
  # pkg:gem/mustermann#lib/mustermann/ast/node.rb:7
  def payload; end

  # Sets the attribute payload
  #
  # @param value the value to set the attribute payload to.
  #
  # pkg:gem/mustermann#lib/mustermann/ast/node.rb:7
  def payload=(_arg0); end

  # Returns the value of attribute start.
  #
  # pkg:gem/mustermann#lib/mustermann/ast/node.rb:7
  def start; end

  # Sets the attribute start
  #
  # @param value the value to set the attribute start to.
  #
  # pkg:gem/mustermann#lib/mustermann/ast/node.rb:7
  def start=(_arg0); end

  # Returns the value of attribute stop.
  #
  # pkg:gem/mustermann#lib/mustermann/ast/node.rb:7
  def stop; end

  # Sets the attribute stop
  #
  # @param value the value to set the attribute stop to.
  #
  # pkg:gem/mustermann#lib/mustermann/ast/node.rb:7
  def stop=(_arg0); end

  # Turns a class name into a node identifier.
  #
  # pkg:gem/mustermann#lib/mustermann/ast/node.rb:90
  def type; end

  class << self
    # @param name [Symbol] of the node
    # @return [Class] factory for the node
    #
    # pkg:gem/mustermann#lib/mustermann/ast/node.rb:12
    def [](name); end

    # @param name [Symbol] of the node
    # @return [String] qualified name of factory for the node
    #
    # pkg:gem/mustermann#lib/mustermann/ast/node.rb:29
    def constant_name(name); end

    # Helper for creating a new instance and calling #parse on it.
    #
    # @return [Mustermann::AST::Node]
    #
    # pkg:gem/mustermann#lib/mustermann/ast/node.rb:38
    def parse(payload = T.unsafe(nil), **options, &block); end

    # Turns a class name into a node identifier.
    #
    # pkg:gem/mustermann#lib/mustermann/ast/node.rb:22
    def type; end
  end
end

# pkg:gem/mustermann#lib/mustermann/ast/node.rb:95
class Mustermann::AST::Node::Capture < ::Mustermann::AST::Node
  # @see Mustermann::AST::Compiler::Capture#default
  #
  # pkg:gem/mustermann#lib/mustermann/ast/node.rb:98
  def constraint; end

  # @see Mustermann::AST::Compiler::Capture#default
  #
  # pkg:gem/mustermann#lib/mustermann/ast/node.rb:98
  def constraint=(_arg0); end

  # @see Mustermann::AST::Pattern#map_param
  #
  # pkg:gem/mustermann#lib/mustermann/ast/node.rb:106
  def convert; end

  # @see Mustermann::AST::Pattern#map_param
  #
  # pkg:gem/mustermann#lib/mustermann/ast/node.rb:106
  def convert=(_arg0); end

  # pkg:gem/mustermann#lib/mustermann/ast/node.rb:116
  def name; end

  # @see Mustermann::AST::Node#parse
  #
  # pkg:gem/mustermann#lib/mustermann/ast/node.rb:110
  def parse; end

  # @see Mustermann::AST::Compiler::Capture#qualified
  #
  # pkg:gem/mustermann#lib/mustermann/ast/node.rb:102
  def qualifier; end

  # @see Mustermann::AST::Compiler::Capture#qualified
  #
  # pkg:gem/mustermann#lib/mustermann/ast/node.rb:102
  def qualifier=(_arg0); end
end

# pkg:gem/mustermann#lib/mustermann/ast/node.rb:120
class Mustermann::AST::Node::Char < ::Mustermann::AST::Node
  # @return [Integer] minimum size for a node
  #
  # pkg:gem/mustermann#lib/mustermann/ast/node.rb:123
  def min_size; end
end

# pkg:gem/mustermann#lib/mustermann/ast/node.rb:136
class Mustermann::AST::Node::Composition < ::Mustermann::AST::Node
  # @return [Composition] a new instance of Composition
  #
  # pkg:gem/mustermann#lib/mustermann/ast/node.rb:138
  def initialize(payload = T.unsafe(nil), **options); end
end

# AST node for template expressions.
#
# pkg:gem/mustermann#lib/mustermann/ast/node.rb:130
class Mustermann::AST::Node::Expression < ::Mustermann::AST::Node
  # Returns the value of attribute operator.
  #
  # pkg:gem/mustermann#lib/mustermann/ast/node.rb:132
  def operator; end

  # Sets the attribute operator
  #
  # @param value the value to set the attribute operator to.
  #
  # pkg:gem/mustermann#lib/mustermann/ast/node.rb:132
  def operator=(_arg0); end
end

# pkg:gem/mustermann#lib/mustermann/ast/node.rb:144
class Mustermann::AST::Node::Group < ::Mustermann::AST::Node::Composition; end

# pkg:gem/mustermann#lib/mustermann/ast/node.rb:195
class Mustermann::AST::Node::NamedSplat < ::Mustermann::AST::Node::Splat
  # @see Mustermann::AST::Node::Capture#name
  #
  # pkg:gem/mustermann#lib/mustermann/ast/node.rb:198
  def name; end
end

# pkg:gem/mustermann#lib/mustermann/ast/node.rb:152
class Mustermann::AST::Node::Optional < ::Mustermann::AST::Node; end

# pkg:gem/mustermann#lib/mustermann/ast/node.rb:156
class Mustermann::AST::Node::Or < ::Mustermann::AST::Node; end

# pkg:gem/mustermann#lib/mustermann/ast/node.rb:160
class Mustermann::AST::Node::Root < ::Mustermann::AST::Node
  # Returns the value of attribute pattern.
  #
  # pkg:gem/mustermann#lib/mustermann/ast/node.rb:162
  def pattern; end

  # Sets the attribute pattern
  #
  # @param value the value to set the attribute pattern to.
  #
  # pkg:gem/mustermann#lib/mustermann/ast/node.rb:162
  def pattern=(_arg0); end

  class << self
    # Will trigger transform.
    #
    # @see Mustermann::AST::Node.parse
    #
    # pkg:gem/mustermann#lib/mustermann/ast/node.rb:168
    def parse(string, &block); end
  end
end

# pkg:gem/mustermann#lib/mustermann/ast/node.rb:177
class Mustermann::AST::Node::Separator < ::Mustermann::AST::Node
  # @return [Integer] minimum size for a node
  #
  # pkg:gem/mustermann#lib/mustermann/ast/node.rb:180
  def min_size; end
end

# pkg:gem/mustermann#lib/mustermann/ast/node.rb:186
class Mustermann::AST::Node::Splat < ::Mustermann::AST::Node::Capture
  # @see Mustermann::AST::Node::Capture#name
  #
  # pkg:gem/mustermann#lib/mustermann/ast/node.rb:189
  def name; end
end

# pkg:gem/mustermann#lib/mustermann/ast/node.rb:148
class Mustermann::AST::Node::Union < ::Mustermann::AST::Node::Composition; end

# AST node for template variables.
#
# pkg:gem/mustermann#lib/mustermann/ast/node.rb:203
class Mustermann::AST::Node::Variable < ::Mustermann::AST::Node::Capture
  # Returns the value of attribute explode.
  #
  # pkg:gem/mustermann#lib/mustermann/ast/node.rb:205
  def explode; end

  # Sets the attribute explode
  #
  # @param value the value to set the attribute explode to.
  #
  # pkg:gem/mustermann#lib/mustermann/ast/node.rb:205
  def explode=(_arg0); end

  # Returns the value of attribute prefix.
  #
  # pkg:gem/mustermann#lib/mustermann/ast/node.rb:205
  def prefix; end

  # Sets the attribute prefix
  #
  # @param value the value to set the attribute prefix to.
  #
  # pkg:gem/mustermann#lib/mustermann/ast/node.rb:205
  def prefix=(_arg0); end
end

# pkg:gem/mustermann#lib/mustermann/ast/node.rb:209
class Mustermann::AST::Node::WithLookAhead < ::Mustermann::AST::Node
  # @return [WithLookAhead] a new instance of WithLookAhead
  #
  # pkg:gem/mustermann#lib/mustermann/ast/node.rb:214
  def initialize(payload, at_end, **options); end

  # Returns the value of attribute at_end.
  #
  # pkg:gem/mustermann#lib/mustermann/ast/node.rb:211
  def at_end; end

  # Sets the attribute at_end
  #
  # @param value the value to set the attribute at_end to.
  #
  # pkg:gem/mustermann#lib/mustermann/ast/node.rb:211
  def at_end=(_arg0); end

  # Returns the value of attribute head.
  #
  # pkg:gem/mustermann#lib/mustermann/ast/node.rb:211
  def head; end

  # Sets the attribute head
  #
  # @param value the value to set the attribute head to.
  #
  # pkg:gem/mustermann#lib/mustermann/ast/node.rb:211
  def head=(_arg0); end
end

# Scans an AST for param converters.
#
# @see Mustermann::AST::Pattern#to_templates
#
# pkg:gem/mustermann#lib/mustermann/ast/param_scanner.rb:9
class Mustermann::AST::ParamScanner < ::Mustermann::AST::Translator
  class << self
    # pkg:gem/mustermann#lib/mustermann/ast/param_scanner.rb:11
    def scan_params(ast); end
  end
end

# pkg:gem/mustermann#lib/mustermann/ast/param_scanner.rb:9
class Mustermann::AST::ParamScanner::NodeTranslator < ::Mustermann::AST::Translator::NodeTranslator
  class << self
    # pkg:gem/mustermann#lib/mustermann/ast/param_scanner.rb:9
    def translator; end
  end
end

# Simple, StringScanner based parser.
#
# pkg:gem/mustermann#lib/mustermann/ast/parser.rb:12
class Mustermann::AST::Parser
  extend ::Forwardable

  # @return [Parser] a new instance of Parser
  #
  # pkg:gem/mustermann#lib/mustermann/ast/parser.rb:49
  def initialize(pattern: T.unsafe(nil), **options); end

  # Returns the value of attribute buffer.
  #
  # pkg:gem/mustermann#lib/mustermann/ast/parser.rb:43
  def buffer; end

  # Create a node for a character we don't have an explicit rule for.
  #
  # @param char [String] the character
  # @return [Mustermann::AST::Node] the node
  #
  # pkg:gem/mustermann#lib/mustermann/ast/parser.rb:80
  def default_node(char); end

  # pkg:gem/mustermann#lib/mustermann/ast/parser.rb:46
  def eos?(*_arg0, **_arg1, &_arg2); end

  # Asserts a regular expression matches what's next on the buffer.
  # Will return corresponding MatchData if regexp includes named captures.
  #
  # @param regexp [Regexp] expected to match
  # @raise [Mustermann::ParseError] if expectation wasn't met
  # @return [String, MatchData] the match
  #
  # pkg:gem/mustermann#lib/mustermann/ast/parser.rb:141
  def expect(regexp, char: T.unsafe(nil), **options); end

  # pkg:gem/mustermann#lib/mustermann/ast/parser.rb:46
  def getch(*_arg0, **_arg1, &_arg2); end

  # sets start on node to start if it's not set to a lower value.
  # sets stop on node to stop if it's not set to a higher value.
  #
  # @return [Mustermann::AST::Node] the node passed as third argument
  #
  # pkg:gem/mustermann#lib/mustermann/ast/parser.rb:100
  def min_size(start, stop, node); end

  # @example
  #   node(:char, 'x').compile =~ 'x' # => true
  # @param type [Symbol] node type
  # @return [Mustermann::AST::Node]
  #
  # pkg:gem/mustermann#lib/mustermann/ast/parser.rb:68
  def node(type, *args, **_arg2, &block); end

  # @param string [String] to be parsed
  # @return [Mustermann::AST::Node] parse tree for string
  #
  # pkg:gem/mustermann#lib/mustermann/ast/parser.rb:56
  def parse(string); end

  # Returns the value of attribute pattern.
  #
  # pkg:gem/mustermann#lib/mustermann/ast/parser.rb:43
  def pattern; end

  # pkg:gem/mustermann#lib/mustermann/ast/parser.rb:46
  def pos(*_arg0, **_arg1, &_arg2); end

  # Reads the next element from the buffer.
  #
  # @return [Mustermann::AST::Node] next element
  #
  # pkg:gem/mustermann#lib/mustermann/ast/parser.rb:87
  def read; end

  # Reads an argument string of the format arg1,args2,key:value
  #
  # pkg:gem/mustermann#lib/mustermann/ast/parser.rb:172
  def read_args(key_separator, close, separator: T.unsafe(nil), symbol_keys: T.unsafe(nil), **options); end

  # Allows to read a string inside brackets. It does not expect the string
  # to start with an opening bracket.
  #
  # @example
  #   buffer.string = "fo<o>>ba<r>"
  #   read_brackets(?<, ?>) # => "fo<o>"
  #   buffer.rest # => "ba<r>"
  #
  # pkg:gem/mustermann#lib/mustermann/ast/parser.rb:154
  def read_brackets(open, close, char: T.unsafe(nil), escape: T.unsafe(nil), quote: T.unsafe(nil), **options); end

  # Read a string until a terminating character, ignoring escaped versions of said character.
  #
  # pkg:gem/mustermann#lib/mustermann/ast/parser.rb:210
  def read_escaped(close, escape: T.unsafe(nil), **options); end

  # Reads a separated list with the ability to quote, escape and add spaces.
  #
  # pkg:gem/mustermann#lib/mustermann/ast/parser.rb:191
  def read_list(*close, separator: T.unsafe(nil), escape: T.unsafe(nil), quotes: T.unsafe(nil), ignore: T.unsafe(nil), **options); end

  # Checks for a potential suffix on the buffer.
  #
  # @param element [Mustermann::AST::Node] node without suffix
  # @return [Mustermann::AST::Node] node with suffix
  #
  # pkg:gem/mustermann#lib/mustermann/ast/parser.rb:112
  def read_suffix(element); end

  # Wrapper around {StringScanner#scan} that turns strings into escaped
  # regular expressions and returns a MatchData if the regexp has any
  # named captures.
  #
  # @param regexp [Regexp, String]
  # @return [String, MatchData, nil]
  # @see StringScanner#scan
  #
  # pkg:gem/mustermann#lib/mustermann/ast/parser.rb:128
  def scan(regexp); end

  # Returns the value of attribute string.
  #
  # pkg:gem/mustermann#lib/mustermann/ast/parser.rb:43
  def string; end

  # Helper for raising an exception for an unexpected character.
  # Will read character from buffer if buffer is passed in.
  #
  # @param char [String, nil] the unexpected character
  # @raise [Mustermann::ParseError, Exception]
  #
  # pkg:gem/mustermann#lib/mustermann/ast/parser.rb:228
  def unexpected(char = T.unsafe(nil), exception: T.unsafe(nil)); end

  class << self
    # Defines another grammar rule for first character.
    #
    # @see Mustermann::Rails
    # @see Mustermann::Sinatra
    # @see Mustermann::Template
    #
    # pkg:gem/mustermann#lib/mustermann/ast/parser.rb:26
    def on(*chars, &block); end

    # @param string [String] to be parsed
    # @return [Mustermann::AST::Node] parse tree for string
    #
    # pkg:gem/mustermann#lib/mustermann/ast/parser.rb:16
    def parse(string, **options); end

    # Defines another grammar rule for a suffix.
    #
    # @see Mustermann::Sinatra
    #
    # pkg:gem/mustermann#lib/mustermann/ast/parser.rb:36
    def suffix(pattern = T.unsafe(nil), after: T.unsafe(nil), &block); end
  end
end

# Superclass for pattern styles that parse an AST from the string pattern.
#
# @abstract
#
# pkg:gem/mustermann#lib/mustermann/ast/pattern.rb:18
class Mustermann::AST::Pattern < ::Mustermann::RegexpBased
  extend ::SingleForwardable

  # pkg:gem/mustermann#lib/mustermann/ast/pattern.rb:23
  def boundaries(*_arg0, **_arg1, &_arg2); end

  # pkg:gem/mustermann#lib/mustermann/ast/pattern.rb:23
  def compiler(*_arg0, **_arg1, &_arg2); end

  # All AST-based pattern implementations support expanding.
  #
  # @example Checking if a pattern supports expanding
  #   if pattern.respond_to? :expand
  #   pattern.expand(name: "foo")
  #   else
  #   warn "does not support expanding"
  #   end
  # @example Expanding a pattern
  #   pattern = Mustermann.new('/:name(.:ext)?')
  #   pattern.expand(name: 'hello')             # => "/hello"
  #   pattern.expand(name: 'hello', ext: 'png') # => "/hello.png"
  # @param behavior [Symbol] What to do with additional key/value pairs not present in the values hash.
  #   Possible options: :raise, :ignore, :append.
  # @param values [Hash{Symbol: #to_s, Array<#to_s>}] Values to use for expansion.
  # @raise [NotImplementedError] raised if expand is not supported.
  # @raise [Mustermann::ExpandError] raised if a value is missing or unknown
  # @return [String] expanded string
  # @see Mustermann::Expander
  # @see Mustermann::Pattern#expand
  #
  # pkg:gem/mustermann#lib/mustermann/ast/pattern.rb:106
  def expand(behavior = T.unsafe(nil), values = T.unsafe(nil)); end

  # @see Mustermann::Pattern#map_param
  #
  # pkg:gem/mustermann#lib/mustermann/ast/pattern.rb:123
  def map_param(key, value); end

  # pkg:gem/mustermann#lib/mustermann/ast/pattern.rb:23
  def param_scanner(*_arg0, **_arg1, &_arg2); end

  # pkg:gem/mustermann#lib/mustermann/ast/pattern.rb:23
  def parser(*_arg0, **_arg1, &_arg2); end

  # pkg:gem/mustermann#lib/mustermann/ast/pattern.rb:23
  def template_generator(*_arg0, **_arg1, &_arg2); end

  # Internal AST representation of pattern.
  #
  # pkg:gem/mustermann#lib/mustermann/ast/pattern.rb:88
  def to_ast; end

  # All AST-based pattern implementations support generating templates.
  #
  # @example Checking if a pattern supports expanding
  #   if pattern.respond_to? :to_templates
  #   pattern.to_templates
  #   else
  #   warn "does not support template generation"
  #   end
  # @example generating templates
  #   Mustermann.new("/:name").to_templates                   # => ["/{name}"]
  #   Mustermann.new("/:foo(@:bar)?/*baz").to_templates       # => ["/{foo}@{bar}/{+baz}", "/{foo}/{+baz}"]
  #   Mustermann.new("/{name}", type: :template).to_templates # => ["/{name}"]
  # @example generating templates from composite patterns
  #   pattern  = Mustermann.new('/:name')
  #   pattern |= Mustermann.new('/{name}', type: :template)
  #   pattern |= Mustermann.new('/example/*nested')
  #   pattern.to_templates # => ["/{name}", "/example/{+nested}"]
  # @return [Array<String>] list of URI templates
  # @see Mustermann::Pattern#to_templates
  #
  # pkg:gem/mustermann#lib/mustermann/ast/pattern.rb:117
  def to_templates; end

  # pkg:gem/mustermann#lib/mustermann/ast/pattern.rb:23
  def transformer(*_arg0, **_arg1, &_arg2); end

  # pkg:gem/mustermann#lib/mustermann/ast/pattern.rb:23
  def validation(*_arg0, **_arg1, &_arg2); end

  private

  # pkg:gem/mustermann#lib/mustermann/ast/pattern.rb:79
  def compile(**options); end

  # pkg:gem/mustermann#lib/mustermann/ast/pattern.rb:24
  def generate_templates(*_arg0, **_arg1, &_arg2); end

  # pkg:gem/mustermann#lib/mustermann/ast/pattern.rb:129
  def param_converters; end

  # pkg:gem/mustermann#lib/mustermann/ast/pattern.rb:24
  def parse(*_arg0, **_arg1, &_arg2); end

  # pkg:gem/mustermann#lib/mustermann/ast/pattern.rb:24
  def scan_params(*_arg0, **_arg1, &_arg2); end

  # pkg:gem/mustermann#lib/mustermann/ast/pattern.rb:24
  def set_boundaries(*_arg0, **_arg1, &_arg2); end

  # pkg:gem/mustermann#lib/mustermann/ast/pattern.rb:24
  def transform(*_arg0, **_arg1, &_arg2); end

  # pkg:gem/mustermann#lib/mustermann/ast/pattern.rb:24
  def validate(*_arg0, **_arg1, &_arg2); end

  class << self
    # @api private
    # @return [#set_boundaries] translator making sure start and stop is set on all nodes
    #
    # pkg:gem/mustermann#lib/mustermann/ast/pattern.rb:46
    def boundaries; end

    # @api private
    # @return [#compile] compiler object for pattern
    #
    # pkg:gem/mustermann#lib/mustermann/ast/pattern.rb:39
    def compiler; end

    # pkg:gem/mustermann#lib/mustermann/ast/pattern.rb:22
    def on(*_arg0, **_arg1, &_arg2); end

    # @api private
    # @return [#scan_params] param scanner for pattern
    #
    # pkg:gem/mustermann#lib/mustermann/ast/pattern.rb:74
    def param_scanner; end

    # @api private
    # @return [#parse] parser object for pattern
    #
    # pkg:gem/mustermann#lib/mustermann/ast/pattern.rb:30
    def parser; end

    # pkg:gem/mustermann#lib/mustermann/ast/pattern.rb:22
    def suffix(*_arg0, **_arg1, &_arg2); end

    # @api private
    # @return [#generate_templates] generates URI templates for pattern
    #
    # pkg:gem/mustermann#lib/mustermann/ast/pattern.rb:67
    def template_generator; end

    # @api private
    # @return [#transform] transformer object for pattern
    #
    # pkg:gem/mustermann#lib/mustermann/ast/pattern.rb:53
    def transformer; end

    # @api private
    # @return [#validate] validation object for pattern
    #
    # pkg:gem/mustermann#lib/mustermann/ast/pattern.rb:60
    def validation; end
  end
end

# Turns an AST into an Array of URI templates representing the AST.
#
# @see Mustermann::AST::Pattern#to_templates
#
# pkg:gem/mustermann#lib/mustermann/ast/template_generator.rb:9
class Mustermann::AST::TemplateGenerator < ::Mustermann::AST::Translator
  class << self
    # pkg:gem/mustermann#lib/mustermann/ast/template_generator.rb:11
    def generate_templates(ast); end
  end
end

# pkg:gem/mustermann#lib/mustermann/ast/template_generator.rb:9
class Mustermann::AST::TemplateGenerator::NodeTranslator < ::Mustermann::AST::Translator::NodeTranslator
  class << self
    # pkg:gem/mustermann#lib/mustermann/ast/template_generator.rb:9
    def translator; end
  end
end

# Takes a tree, turns it into an even better tree.
#
# pkg:gem/mustermann#lib/mustermann/ast/transformer.rb:8
class Mustermann::AST::Transformer < ::Mustermann::AST::Translator
  class << self
    # Transforms a tree.
    #
    # @note might mutate handed in tree instead of creating a new one
    # @param tree [Mustermann::AST::Node] to be transformed
    # @return [Mustermann::AST::Node] transformed tree
    #
    # pkg:gem/mustermann#lib/mustermann/ast/transformer.rb:15
    def transform(tree); end
  end
end

# Inserts with_look_ahead nodes wherever appropriate
#
# pkg:gem/mustermann#lib/mustermann/ast/transformer.rb:105
class Mustermann::AST::Transformer::ArrayTransform < ::Mustermann::AST::Transformer::NodeTranslator
  # turn look ahead buffer into look ahead node
  #
  # pkg:gem/mustermann#lib/mustermann/ast/transformer.rb:142
  def create_lookahead(elements, *args); end

  # can the current element deal with a look-ahead?
  #
  # @return [Boolean]
  #
  # pkg:gem/mustermann#lib/mustermann/ast/transformer.rb:166
  def expect_lookahead?(element); end

  # helper method for deciding where to put an element for now
  #
  # pkg:gem/mustermann#lib/mustermann/ast/transformer.rb:173
  def list_for(element); end

  # can the given element be used in a look-ahead?
  #
  # @return [Boolean]
  #
  # pkg:gem/mustermann#lib/mustermann/ast/transformer.rb:149
  def lookahead?(element, in_lookahead = T.unsafe(nil)); end

  # buffer for potential look ahead
  #
  # pkg:gem/mustermann#lib/mustermann/ast/transformer.rb:116
  def lookahead_buffer; end

  # does the list of elements look look-ahead-ish to you?
  #
  # @return [Boolean]
  #
  # pkg:gem/mustermann#lib/mustermann/ast/transformer.rb:159
  def lookahead_payload?(payload, in_lookahead); end

  # the new array
  #
  # pkg:gem/mustermann#lib/mustermann/ast/transformer.rb:110
  def payload; end

  # handle a single element from the array
  #
  # pkg:gem/mustermann#lib/mustermann/ast/transformer.rb:129
  def track(element); end

  # transform the array
  #
  # pkg:gem/mustermann#lib/mustermann/ast/transformer.rb:122
  def translate; end
end

# URI expression transformations depending on operator
#
# pkg:gem/mustermann#lib/mustermann/ast/transformer.rb:76
class Mustermann::AST::Transformer::ExpressionTransform < ::Mustermann::AST::Transformer::NodeTranslator
  # Sets operator and inserts separators in between variables.
  #
  # pkg:gem/mustermann#lib/mustermann/ast/transformer.rb:93
  def translate; end
end

# pkg:gem/mustermann#lib/mustermann/ast/transformer.rb:84
Mustermann::AST::Transformer::ExpressionTransform::OPERATORS = T.let(T.unsafe(nil), Hash)

# pkg:gem/mustermann#lib/mustermann/ast/transformer.rb:80
class Mustermann::AST::Transformer::ExpressionTransform::Operator < ::Struct
  # pkg:gem/mustermann#lib/mustermann/ast/transformer.rb:80
  def allow_reserved; end

  # pkg:gem/mustermann#lib/mustermann/ast/transformer.rb:80
  def allow_reserved=(_); end

  # pkg:gem/mustermann#lib/mustermann/ast/transformer.rb:80
  def parametric; end

  # pkg:gem/mustermann#lib/mustermann/ast/transformer.rb:80
  def parametric=(_); end

  # pkg:gem/mustermann#lib/mustermann/ast/transformer.rb:80
  def prefix; end

  # pkg:gem/mustermann#lib/mustermann/ast/transformer.rb:80
  def prefix=(_); end

  # pkg:gem/mustermann#lib/mustermann/ast/transformer.rb:80
  def separator; end

  # pkg:gem/mustermann#lib/mustermann/ast/transformer.rb:80
  def separator=(_); end

  class << self
    # pkg:gem/mustermann#lib/mustermann/ast/transformer.rb:80
    def [](*_arg0); end

    # pkg:gem/mustermann#lib/mustermann/ast/transformer.rb:80
    def inspect; end

    # pkg:gem/mustermann#lib/mustermann/ast/transformer.rb:80
    def keyword_init?; end

    # pkg:gem/mustermann#lib/mustermann/ast/transformer.rb:80
    def members; end

    # pkg:gem/mustermann#lib/mustermann/ast/transformer.rb:80
    def new(*_arg0); end
  end
end

# turn a group containing or nodes into a union
#
# pkg:gem/mustermann#lib/mustermann/ast/transformer.rb:30
class Mustermann::AST::Transformer::GroupTransformer < ::Mustermann::AST::Transformer::NodeTranslator
  # pkg:gem/mustermann#lib/mustermann/ast/transformer.rb:48
  def group(elements); end

  # pkg:gem/mustermann#lib/mustermann/ast/transformer.rb:55
  def split_payload; end

  # pkg:gem/mustermann#lib/mustermann/ast/transformer.rb:34
  def translate; end

  # pkg:gem/mustermann#lib/mustermann/ast/transformer.rb:42
  def union; end
end

# pkg:gem/mustermann#lib/mustermann/ast/transformer.rb:8
class Mustermann::AST::Transformer::NodeTranslator < ::Mustermann::AST::Translator::NodeTranslator
  class << self
    # pkg:gem/mustermann#lib/mustermann/ast/transformer.rb:8
    def translator; end
  end
end

# inject a union node right inside the root node if it contains or nodes
#
# pkg:gem/mustermann#lib/mustermann/ast/transformer.rb:64
class Mustermann::AST::Transformer::RootTransformer < ::Mustermann::AST::Transformer::GroupTransformer
  # pkg:gem/mustermann#lib/mustermann/ast/transformer.rb:68
  def union; end
end

# Implements translator pattern
#
# @abstract
#
# pkg:gem/mustermann#lib/mustermann/ast/translator.rb:13
class Mustermann::AST::Translator
  # @param node [Mustermann::AST::Node, Object] to translate
  # @raise [error_class]
  # @return decorator encapsulating translation
  #
  # pkg:gem/mustermann#lib/mustermann/ast/translator.rb:108
  def decorator_for(node); end

  # pkg:gem/mustermann#lib/mustermann/ast/translator.rb:70
  def error_class; end

  # @return [String] escaped character
  #
  # pkg:gem/mustermann#lib/mustermann/ast/translator.rb:124
  def escape(char, parser: T.unsafe(nil), escape: T.unsafe(nil), also_escape: T.unsafe(nil)); end

  # Start the translation dance for a (sub)tree.
  #
  # pkg:gem/mustermann#lib/mustermann/ast/translator.rb:116
  def translate(node, *args, **_arg2, &block); end

  class << self
    # Enables quick creation of a translator object.
    #
    # @example
    #   require 'mustermann'
    #   require 'mustermann/ast/translator'
    #
    #   translator = Mustermann::AST::Translator.create do
    #   translate(:node)  { [type, *t(payload)].flatten.compact }
    #   translate(Array)  { map { |e| t(e) } }
    #   translate(Object) { }
    #   end
    #
    #   ast = Mustermann.new('/:name').to_ast
    #   translator.translate(ast) # => [:root, :separator, :capture]
    #
    # pkg:gem/mustermann#lib/mustermann/ast/translator.rb:98
    def create(&block); end

    # maps types to translations
    #
    # pkg:gem/mustermann#lib/mustermann/ast/translator.rb:54
    def dispatch_table; end

    # some magic sauce so {NodeTranslator}s know whom to talk to for {#register}
    #
    # pkg:gem/mustermann#lib/mustermann/ast/translator.rb:60
    def inherited(subclass); end

    # DSL-ish method for specifying the exception class to use.
    #
    # pkg:gem/mustermann#lib/mustermann/ast/translator.rb:69
    def raises(error); end

    # DSL method for defining single method translations.
    #
    # pkg:gem/mustermann#lib/mustermann/ast/translator.rb:75
    def translate(*types, &block); end
  end
end

# Encapsulates a single node translation
#
# pkg:gem/mustermann#lib/mustermann/ast/translator.rb:19
class Mustermann::AST::Translator::NodeTranslator
  # @param node [Mustermann::AST::Node, Object]
  # @param translator [Mustermann::AST::Translator]
  # @return [NodeTranslator] a new instance of NodeTranslator
  #
  # pkg:gem/mustermann#lib/mustermann/ast/translator.rb:33
  def initialize(node, translator); end

  # pkg:gem/mustermann#lib/mustermann/ast/translator.rb:49
  def node; end

  # shorthand for translating a nested object
  #
  # pkg:gem/mustermann#lib/mustermann/ast/translator.rb:43
  def t(*args, **_arg1, &block); end

  # Returns the value of attribute translator.
  #
  # pkg:gem/mustermann#lib/mustermann/ast/translator.rb:39
  def translator; end

  class << self
    # @param types [Array<Symbol, Class>] list of types to register for.
    #
    # pkg:gem/mustermann#lib/mustermann/ast/translator.rb:22
    def register(*types); end
  end
end

# pkg:gem/mustermann#lib/mustermann/ast/translator.rb:15
Mustermann::AST::Translator::URI_PARSER = T.let(T.unsafe(nil), URI::RFC2396_Parser)

# Checks the AST for certain validations, like correct capture names.
#
# Internally a poor man's visitor (abusing translator to not have to implement a visitor).
#
# pkg:gem/mustermann#lib/mustermann/ast/validation.rb:10
class Mustermann::AST::Validation < ::Mustermann::AST::Translator
  # @raise [Mustermann::CompileError] if name is not acceptable
  #
  # pkg:gem/mustermann#lib/mustermann/ast/validation.rb:30
  def check_name(name, forbidden: T.unsafe(nil)); end

  # @return [Array<String>] list of capture names in tree
  #
  # pkg:gem/mustermann#lib/mustermann/ast/validation.rb:40
  def names; end

  class << self
    # Runs validations.
    #
    # @param ast [Mustermann::AST::Node] to be validated
    # @raise [Mustermann::AST::CompileError] if validation fails
    # @return [Mustermann::AST::Node] the validated ast
    #
    # pkg:gem/mustermann#lib/mustermann/ast/validation.rb:17
    def validate(ast); end
  end
end

# pkg:gem/mustermann#lib/mustermann/ast/validation.rb:10
class Mustermann::AST::Validation::NodeTranslator < ::Mustermann::AST::Translator::NodeTranslator
  class << self
    # pkg:gem/mustermann#lib/mustermann/ast/validation.rb:10
    def translator; end
  end
end

# Class for defining and running simple Hash transformations.
#
# @example
#   caster = Mustermann::Caster.new
#   caster.register(:foo) { |value| { bar: value.upcase } }
#   caster.cast(foo: "hello", baz: "world") # => { bar: "HELLO", baz: "world" }
# @see Mustermann::Expander#cast
#
# pkg:gem/mustermann#lib/mustermann/caster.rb:15
class Mustermann::Caster
  # @param types [Array<Symbol, Regexp, #cast, #===>] identifier for cast type (some need block)
  # @return [Caster] a new instance of Caster
  #
  # pkg:gem/mustermann#lib/mustermann/caster.rb:18
  def initialize(*types, &block); end

  # Transforms a Hash.
  #
  # @param hash [Hash] pre-transform Hash
  # @return [Hash] post-transform Hash
  #
  # pkg:gem/mustermann#lib/mustermann/caster.rb:45
  def cast(hash); end

  # @param type [Symbol, Regexp, #cast, #===] identifier for cast type (some need block)
  # @return [#cast] specific cast operation
  #
  # pkg:gem/mustermann#lib/mustermann/caster.rb:34
  def caster_for(type, &block); end

  # @param types [Array<Symbol, Regexp, #cast, #===>] identifier for cast type (some need block)
  #
  # pkg:gem/mustermann#lib/mustermann/caster.rb:25
  def register(*types, &block); end
end

# Class for block based casts that are triggered for every key/value pair.
#
# pkg:gem/mustermann#lib/mustermann/caster.rb:58
class Mustermann::Caster::Any
  # @return [Any] a new instance of Any
  #
  # pkg:gem/mustermann#lib/mustermann/caster.rb:60
  def initialize(&block); end

  # @see Mustermann::Caster#cast
  #
  # pkg:gem/mustermann#lib/mustermann/caster.rb:66
  def cast(key, value); end
end

# Class for block based casts that are triggered for key/value pairs with a matching key.
#
# pkg:gem/mustermann#lib/mustermann/caster.rb:94
class Mustermann::Caster::Key < ::Mustermann::Caster::Any
  # @param type [#===] used for matching keys
  # @return [Key] a new instance of Key
  #
  # pkg:gem/mustermann#lib/mustermann/caster.rb:97
  def initialize(type, &block); end

  # @see Mustermann::Caster#cast
  #
  # pkg:gem/mustermann#lib/mustermann/caster.rb:104
  def cast(key, value); end
end

# Class for block based casts that are triggered for key/value pairs with a matching value.
#
# pkg:gem/mustermann#lib/mustermann/caster.rb:77
class Mustermann::Caster::Value < ::Mustermann::Caster::Any
  # @param type [#===] used for matching values
  # @return [Value] a new instance of Value
  #
  # pkg:gem/mustermann#lib/mustermann/caster.rb:80
  def initialize(type, &block); end

  # @see Mustermann::Caster#cast
  #
  # pkg:gem/mustermann#lib/mustermann/caster.rb:87
  def cast(key, value); end
end

# Raised if anything goes wrong while compiling a {Pattern}.
#
# pkg:gem/mustermann#lib/mustermann/error.rb:5
class Mustermann::CompileError < ::Mustermann::Error; end

# Class for pattern objects composed of multiple patterns using binary logic.
#
# @see Mustermann::Pattern#&
# @see Mustermann::Pattern#^
# @see Mustermann::Pattern#|
#
# pkg:gem/mustermann#lib/mustermann/composite.rb:7
class Mustermann::Composite < ::Mustermann::Pattern
  # @return [Composite] a new instance of Composite
  #
  # pkg:gem/mustermann#lib/mustermann/composite.rb:27
  def initialize(patterns, operator: T.unsafe(nil), **options); end

  # @see Mustermann::Pattern#==
  #
  # pkg:gem/mustermann#lib/mustermann/composite.rb:33
  def ==(pattern); end

  # @see Mustermann::Pattern#===
  #
  # pkg:gem/mustermann#lib/mustermann/composite.rb:48
  def ===(string); end

  # @return [Boolean]
  # @see Mustermann::Pattern#eql?
  #
  # pkg:gem/mustermann#lib/mustermann/composite.rb:38
  def eql?(pattern); end

  # Expanding is supported by almost all patterns (notable exceptions are {Mustermann::Shell},
  # {Mustermann::Regular} and {Mustermann::Simple}).
  #
  # Union {Mustermann::Composite} patterns (with the | operator) support expanding if all
  # patterns they are composed of also support it.
  #
  # @example Checking if a pattern supports expanding
  #   if pattern.respond_to? :expand
  #   pattern.expand(name: "foo")
  #   else
  #   warn "does not support expanding"
  #   end
  # @example Expanding a pattern
  #   pattern = Mustermann.new('/:name(.:ext)?')
  #   pattern.expand(name: 'hello')             # => "/hello"
  #   pattern.expand(name: 'hello', ext: 'png') # => "/hello.png"
  # @note This method is only implemented by certain subclasses.
  # @param behavior [Symbol] What to do with additional key/value pairs not present in the values hash.
  #   Possible options: :raise, :ignore, :append.
  # @param values [Hash{Symbol: #to_s, Array<#to_s>}] Values to use for expansion.
  # @raise [NotImplementedError] raised if expand is not supported.
  # @raise [Mustermann::ExpandError] raised if a value is missing or unknown
  # @return [String] expanded string
  # @see Mustermann::Expander
  #
  # pkg:gem/mustermann#lib/mustermann/composite.rb:69
  def expand(behavior = T.unsafe(nil), values = T.unsafe(nil)); end

  # @see Mustermann::Pattern#hash
  #
  # pkg:gem/mustermann#lib/mustermann/composite.rb:43
  def hash; end

  # pkg:gem/mustermann#lib/mustermann/composite.rb:87
  def inspect; end

  # @see Mustermann::Pattern#match
  #
  # pkg:gem/mustermann#lib/mustermann/composite.rb:58
  def match(string); end

  # Returns the value of attribute operator.
  #
  # pkg:gem/mustermann#lib/mustermann/composite.rb:8
  def operator; end

  # @see Mustermann::Pattern#params
  #
  # pkg:gem/mustermann#lib/mustermann/composite.rb:53
  def params(string); end

  # Returns the value of attribute patterns.
  #
  # pkg:gem/mustermann#lib/mustermann/composite.rb:8
  def patterns; end

  # @return [Boolean]
  #
  # pkg:gem/mustermann#lib/mustermann/composite.rb:63
  def respond_to_special?(method); end

  # pkg:gem/mustermann#lib/mustermann/composite.rb:92
  def simple_inspect; end

  # @return [String] the string representation of the pattern
  #
  # pkg:gem/mustermann#lib/mustermann/composite.rb:82
  def to_s; end

  # Generates a list of URI template strings representing the pattern.
  #
  # Note that this transformation is lossy and the strings matching these
  # templates might not match the pattern (and vice versa).
  #
  # This comes in quite handy since URI templates are not made for pattern matching.
  # That way you can easily use a more precise template syntax and have it automatically
  # generate hypermedia links for you.
  #
  # Template generation is supported by almost all patterns (notable exceptions are
  # {Mustermann::Shell}, {Mustermann::Regular} and {Mustermann::Simple}).
  # Union {Mustermann::Composite} patterns (with the | operator) support template generation
  # if all patterns they are composed of also support it.
  #
  # @example Checking if a pattern supports expanding
  #   if pattern.respond_to? :to_templates
  #   pattern.to_templates
  #   else
  #   warn "does not support template generation"
  #   end
  # @example generating templates
  #   Mustermann.new("/:name").to_templates                   # => ["/{name}"]
  #   Mustermann.new("/:foo(@:bar)?/*baz").to_templates       # => ["/{foo}@{bar}/{+baz}", "/{foo}/{+baz}"]
  #   Mustermann.new("/{name}", type: :template).to_templates # => ["/{name}"]
  # @example generating templates from composite patterns
  #   pattern  = Mustermann.new('/:name')
  #   pattern |= Mustermann.new('/{name}', type: :template)
  #   pattern |= Mustermann.new('/example/*nested')
  #   pattern.to_templates # => ["/{name}", "/example/{+nested}"]
  # @note This method is only implemented by certain subclasses.
  # @return [Array<String>] list of URI templates
  #
  # pkg:gem/mustermann#lib/mustermann/composite.rb:76
  def to_templates; end

  private

  # pkg:gem/mustermann#lib/mustermann/composite.rb:105
  def patterns_from(pattern, **options); end

  # pkg:gem/mustermann#lib/mustermann/composite.rb:98
  def with_matching(string, method); end

  class << self
    # @return [Mustermann::Pattern] a new composite pattern
    #
    # pkg:gem/mustermann#lib/mustermann/composite.rb:18
    def new(*patterns, **options); end

    # @return [Boolean]
    # @see Mustermann::Pattern.supported?
    #
    # pkg:gem/mustermann#lib/mustermann/composite.rb:12
    def supported?(option, type: T.unsafe(nil), **options); end
  end
end

# Class for pattern objects that are a concatenation of other patterns.
#
# @see Mustermann::Pattern#+
#
# pkg:gem/mustermann#lib/mustermann/concat.rb:5
class Mustermann::Concat < ::Mustermann::Composite
  # Should not be used directly.
  #
  # @return [Concat] a new instance of Concat
  #
  # pkg:gem/mustermann#lib/mustermann/concat.rb:43
  def initialize(*_arg0, **_arg1); end

  # @see Mustermann::Pattern#===
  #
  # pkg:gem/mustermann#lib/mustermann/concat.rb:55
  def ===(string); end

  # Expanding is supported by almost all patterns (notable exceptions are {Mustermann::Shell},
  # {Mustermann::Regular} and {Mustermann::Simple}).
  #
  # Union {Mustermann::Composite} patterns (with the | operator) support expanding if all
  # patterns they are composed of also support it.
  #
  # @example Checking if a pattern supports expanding
  #   if pattern.respond_to? :expand
  #   pattern.expand(name: "foo")
  #   else
  #   warn "does not support expanding"
  #   end
  # @example Expanding a pattern
  #   pattern = Mustermann.new('/:name(.:ext)?')
  #   pattern.expand(name: 'hello')             # => "/hello"
  #   pattern.expand(name: 'hello', ext: 'png') # => "/hello.png"
  # @note This method is only implemented by certain subclasses.
  # @param behavior [Symbol] What to do with additional key/value pairs not present in the values hash.
  #   Possible options: :raise, :ignore, :append.
  # @param values [Hash{Symbol: #to_s, Array<#to_s>}] Values to use for expansion.
  # @raise [NotImplementedError] raised if expand is not supported.
  # @raise [Mustermann::ExpandError] raised if a value is missing or unknown
  # @return [String] expanded string
  # @see Mustermann::Expander
  #
  # pkg:gem/mustermann#lib/mustermann/concat.rb:90
  def expand(behavior = T.unsafe(nil), values = T.unsafe(nil)); end

  # @see Mustermann::Pattern#match
  #
  # pkg:gem/mustermann#lib/mustermann/concat.rb:60
  def match(string); end

  # @return [Symbol] always :+
  # @see Mustermann::Composite#operator
  #
  # pkg:gem/mustermann#lib/mustermann/concat.rb:50
  def operator; end

  # @see Mustermann::Pattern#params
  #
  # pkg:gem/mustermann#lib/mustermann/concat.rb:66
  def params(string); end

  # @see Mustermann::Pattern#peek_match
  #
  # pkg:gem/mustermann#lib/mustermann/concat.rb:77
  def peek_match(string); end

  # @see Mustermann::Pattern#peek_params
  #
  # pkg:gem/mustermann#lib/mustermann/concat.rb:85
  def peek_params(string); end

  # @see Mustermann::Pattern#peek_size
  #
  # pkg:gem/mustermann#lib/mustermann/concat.rb:72
  def peek_size(string); end

  # @return [Boolean]
  #
  # pkg:gem/mustermann#lib/mustermann/concat.rb:103
  def respond_to_special?(method); end

  # Generates a list of URI template strings representing the pattern.
  #
  # Note that this transformation is lossy and the strings matching these
  # templates might not match the pattern (and vice versa).
  #
  # This comes in quite handy since URI templates are not made for pattern matching.
  # That way you can easily use a more precise template syntax and have it automatically
  # generate hypermedia links for you.
  #
  # Template generation is supported by almost all patterns (notable exceptions are
  # {Mustermann::Shell}, {Mustermann::Regular} and {Mustermann::Simple}).
  # Union {Mustermann::Composite} patterns (with the | operator) support template generation
  # if all patterns they are composed of also support it.
  #
  # @example Checking if a pattern supports expanding
  #   if pattern.respond_to? :to_templates
  #   pattern.to_templates
  #   else
  #   warn "does not support template generation"
  #   end
  # @example generating templates
  #   Mustermann.new("/:name").to_templates                   # => ["/{name}"]
  #   Mustermann.new("/:foo(@:bar)?/*baz").to_templates       # => ["/{foo}@{bar}/{+baz}", "/{foo}/{+baz}"]
  #   Mustermann.new("/{name}", type: :template).to_templates # => ["/{name}"]
  # @example generating templates from composite patterns
  #   pattern  = Mustermann.new('/:name')
  #   pattern |= Mustermann.new('/{name}', type: :template)
  #   pattern |= Mustermann.new('/example/*nested')
  #   pattern.to_templates # => ["/{name}", "/example/{+nested}"]
  # @note This method is only implemented by certain subclasses.
  # @return [Array<String>] list of URI templates
  #
  # pkg:gem/mustermann#lib/mustermann/concat.rb:97
  def to_templates; end

  private

  # generates one big AST from all patterns
  # will not check if patterns support AST generation
  #
  # pkg:gem/mustermann#lib/mustermann/concat.rb:129
  def combined_ast; end

  # used to generate results for various methods by scanning through an input string
  #
  # pkg:gem/mustermann#lib/mustermann/concat.rb:110
  def pump(string, inject_with: T.unsafe(nil), initial: T.unsafe(nil), with_size: T.unsafe(nil)); end
end

# Mixin for patterns to support native concatenation.
#
# pkg:gem/mustermann#lib/mustermann/concat.rb:8
module Mustermann::Concat::Native
  # @see Mustermann::Pattern#+
  #
  # pkg:gem/mustermann#lib/mustermann/concat.rb:11
  def +(other); end

  # pkg:gem/mustermann#lib/mustermann/concat.rb:23
  def look_ahead(other); end

  private

  # pkg:gem/mustermann#lib/mustermann/concat.rb:29
  def native_concat(other); end

  # @return [Boolean]
  #
  # pkg:gem/mustermann#lib/mustermann/concat.rb:34
  def native_concat?(other); end
end

# Type to use if no type is given.
#
# @api private
#
# pkg:gem/mustermann#lib/mustermann.rb:13
Mustermann::DEFAULT_TYPE = T.let(T.unsafe(nil), Symbol)

# A simple wrapper around ObjectSpace::WeakMap that allows matching keys by equality rather than identity.
# Used for caching. Note that `fetch` is not guaranteed to return the object, even if it has not been
# garbage collected yet, especially when used concurrently. Therefore, the block passed to `fetch` has to
# be idempotent.
#
# @example
#   class ExpensiveComputation
#   @map = Mustermann::EqualityMap.new
#
#   def self.new(*args)
#   @map.fetch(args) { super }
#   end
#   end
# @see #fetch
#
# pkg:gem/mustermann#lib/mustermann/equality_map.rb:18
class Mustermann::EqualityMap
  # @return [EqualityMap] a new instance of EqualityMap
  #
  # pkg:gem/mustermann#lib/mustermann/equality_map.rb:25
  def initialize; end

  # @param key [#hash] for caching
  # @return value stored in map or result of block
  # @yield block that will be called to populate entry if missing (has to be idempotent)
  #
  # pkg:gem/mustermann#lib/mustermann/equality_map.rb:33
  def fetch(key); end

  # Returns the value of attribute map.
  #
  # pkg:gem/mustermann#lib/mustermann/equality_map.rb:19
  def map; end

  private

  # Finalizer proc needs to be generated in different scope so it doesn't keep a reference to the object.
  #
  # @param hash [Integer] for key
  # @return [Proc] finalizer callback
  #
  # pkg:gem/mustermann#lib/mustermann/equality_map.rb:60
  def finalizer(hash); end

  # @param key [#hash] for identifying the object
  # @param object [Object] to be stored
  # @return [Object] same as the second parameter
  #
  # pkg:gem/mustermann#lib/mustermann/equality_map.rb:49
  def track(key, object); end

  class << self
    # pkg:gem/mustermann#lib/mustermann/equality_map.rb:21
    def new; end
  end
end

# Raised if anything goes wrong while generating a {Pattern}.
#
# pkg:gem/mustermann#lib/mustermann/error.rb:4
class Mustermann::Error < ::StandardError; end

# Raised if anything goes wrong while expanding a {Pattern}.
#
# pkg:gem/mustermann#lib/mustermann/error.rb:7
class Mustermann::ExpandError < ::Mustermann::Error; end

# Allows fine-grained control over pattern expansion.
#
# @example
#   expander = Mustermann::Expander.new(additional_values: :append)
#   expander << "/users/:user_id"
#   expander << "/pages/:page_id"
#
#   expander.expand(page_id: 58, format: :html5) # => "/pages/58?format=html5"
#
# pkg:gem/mustermann#lib/mustermann/expander.rb:15
class Mustermann::Expander
  # @param additional_values [Symbol] behavior when encountering additional values, see {#expand}.
  # @param options [Hash] used when creating/expanding patterns, see {Mustermann.new}.
  # @param patterns [Array<#to_str, Mustermann::Pattern>] list of patterns to expand, see {#add}.
  # @return [Expander] a new instance of Expander
  #
  # pkg:gem/mustermann#lib/mustermann/expander.rb:21
  def initialize(*patterns, additional_values: T.unsafe(nil), **options, &block); end

  # Add patterns to expand.
  #
  # @example
  #   expander = Mustermann::Expander.new
  #   expander.add("/:a.jpg", "/:b.png")
  #   expander.expand(a: "pony") # => "/pony.jpg"
  # @param patterns [Array<#to_str, Mustermann::Pattern>] list of to add for expansion, Strings will be compiled to patterns.
  # @return [Mustermann::Expander] the expander
  #
  # pkg:gem/mustermann#lib/mustermann/expander.rb:57
  def <<(*patterns); end

  # @see Object#==
  #
  # pkg:gem/mustermann#lib/mustermann/expander.rb:158
  def ==(other); end

  # Add patterns to expand.
  #
  # @example
  #   expander = Mustermann::Expander.new
  #   expander.add("/:a.jpg", "/:b.png")
  #   expander.expand(a: "pony") # => "/pony.jpg"
  # @param patterns [Array<#to_str, Mustermann::Pattern>] list of to add for expansion, Strings will be compiled to patterns.
  # @return [Mustermann::Expander] the expander
  #
  # pkg:gem/mustermann#lib/mustermann/expander.rb:43
  def add(*patterns); end

  # Returns the value of attribute additional_values.
  #
  # pkg:gem/mustermann#lib/mustermann/expander.rb:16
  def additional_values; end

  # Register a block as simple hash transformation that runs before expanding the pattern.
  #
  # @overload cast
  # @overload cast
  # @overload cast
  # @return [Mustermann::Expander] the expander
  #
  # pkg:gem/mustermann#lib/mustermann/expander.rb:115
  def cast(*types, &block); end

  # @return [Boolean]
  # @see Object#eql?
  #
  # pkg:gem/mustermann#lib/mustermann/expander.rb:164
  def eql?(other); end

  # @example Expanding a pattern
  #   pattern = Mustermann::Expander.new('/:name', '/:name.:ext')
  #   pattern.expand(name: 'hello')             # => "/hello"
  #   pattern.expand(name: 'hello', ext: 'png') # => "/hello.png"
  # @example Handling additional values
  #   pattern = Mustermann::Expander.new('/:name', '/:name.:ext')
  #   pattern.expand(:ignore, name: 'hello', ext: 'png', scale: '2x') # => "/hello.png"
  #   pattern.expand(:append, name: 'hello', ext: 'png', scale: '2x') # => "/hello.png?scale=2x"
  #   pattern.expand(:raise,  name: 'hello', ext: 'png', scale: '2x') # raises Mustermann::ExpandError
  # @example Setting additional values behavior for the expander object
  #   pattern = Mustermann::Expander.new('/:name', '/:name.:ext', additional_values: :append)
  #   pattern.expand(name: 'hello', ext: 'png', scale: '2x') # => "/hello.png?scale=2x"
  # @param behavior [Symbol] What to do with additional key/value pairs not present in the values hash.
  #   Possible options: :raise, :ignore, :append.
  # @param values [Hash{Symbol: #to_s, Array<#to_s>}] Values to use for expansion.
  # @raise [NotImplementedError] raised if expand is not supported.
  # @raise [Mustermann::ExpandError] raised if a value is missing or unknown
  # @return [String] expanded string
  #
  # pkg:gem/mustermann#lib/mustermann/expander.rb:145
  def expand(behavior = T.unsafe(nil), values = T.unsafe(nil)); end

  # @return [Boolean]
  #
  # pkg:gem/mustermann#lib/mustermann/expander.rb:174
  def expandable?(values); end

  # @see Object#hash
  #
  # pkg:gem/mustermann#lib/mustermann/expander.rb:170
  def hash; end

  # Returns the value of attribute patterns.
  #
  # pkg:gem/mustermann#lib/mustermann/expander.rb:16
  def patterns; end

  private

  # pkg:gem/mustermann#lib/mustermann/expander.rb:195
  def append(uri, values); end

  # Returns the value of attribute caster.
  #
  # pkg:gem/mustermann#lib/mustermann/expander.rb:16
  def caster; end

  # pkg:gem/mustermann#lib/mustermann/expander.rb:201
  def map_values(values); end

  # pkg:gem/mustermann#lib/mustermann/expander.rb:191
  def slice(hash, keys); end

  # pkg:gem/mustermann#lib/mustermann/expander.rb:185
  def split_values(values); end

  # @yield [expand(:raise, slice(values, expandable)), slice(values, non_expandable)]
  #
  # pkg:gem/mustermann#lib/mustermann/expander.rb:180
  def with_rest(values); end
end

# Raised if anything goes wrong while parsing a {Pattern}.
#
# pkg:gem/mustermann#lib/mustermann/error.rb:6
class Mustermann::ParseError < ::Mustermann::Error; end

# Superclass for all pattern implementations.
#
# @abstract
#
# pkg:gem/mustermann#lib/mustermann/pattern.rb:10
class Mustermann::Pattern
  include ::Mustermann

  # @overload initialize
  # @param options [Hash] options for fine-tuning the pattern behavior
  # @param string [String] the string representation of the pattern
  # @raise [Mustermann::Error] if the pattern can't be generated from the string
  # @return [Pattern] a new instance of Pattern
  # @see Mustermann.new
  # @see file:README.md#Types_and_Options "Types and Options" in the README
  #
  # pkg:gem/mustermann#lib/mustermann/pattern.rb:75
  def initialize(string, uri_decode: T.unsafe(nil), **options); end

  # @overload &
  # @overload ^
  # @overload |
  # @param other [Mustermann::Pattern, String] the other pattern
  # @return [Mustermann::Pattern] a composite pattern
  #
  # pkg:gem/mustermann#lib/mustermann/pattern.rb:319
  def &(other); end

  # Creates a concatenated pattern by combingin self with the other pattern supplied.
  # Patterns of different types can be mixed. The availability of `to_templates` and
  # `expand` depends on the patterns being concatenated.
  #
  # String input is treated as identity pattern.
  #
  # @example
  #   require 'mustermann'
  #   prefix = Mustermann.new("/:prefix")
  #   about  = prefix + "/about"
  #   about.params("/main/about") # => {"prefix" => "main"}
  # @param other [Mustermann::Pattern, String] pattern to be appended
  # @return [Mustermann::Pattern] concatenated pattern
  #
  # pkg:gem/mustermann#lib/mustermann/pattern.rb:336
  def +(other); end

  # Two patterns are considered equal if they are of the same type, have the same pattern string
  # and the same options.
  #
  # @return [true, false]
  #
  # pkg:gem/mustermann#lib/mustermann/pattern.rb:119
  def ==(other); end

  # @note Needs to be overridden by subclass.
  # @param string [String] The string to match against
  # @raise [NotImplementedError]
  # @return [Boolean] Whether or not the pattern matches the given string
  # @see http://ruby-doc.org/core-2.0/Regexp.html#method-i-3D-3D-3D Regexp#===
  #
  # pkg:gem/mustermann#lib/mustermann/pattern.rb:106
  def ===(string); end

  # @param string [String] The string to match against
  # @return [Integer, nil] nil if pattern does not match the string, zero if it does.
  # @see http://ruby-doc.org/core-2.0/Regexp.html#method-i-3D-7E Regexp#=~
  #
  # pkg:gem/mustermann#lib/mustermann/pattern.rb:98
  def =~(string); end

  # @overload &
  # @overload ^
  # @overload |
  # @param other [Mustermann::Pattern, String] the other pattern
  # @return [Mustermann::Pattern] a composite pattern
  #
  # pkg:gem/mustermann#lib/mustermann/pattern.rb:320
  def ^(other); end

  # @return [Boolean]
  #
  # pkg:gem/mustermann#lib/mustermann/pattern.rb:391
  def always_array?(key); end

  # Two patterns are considered equal if they are of the same type, have the same pattern string
  # and the same options.
  #
  # @return [true, false]
  #
  # pkg:gem/mustermann#lib/mustermann/pattern.rb:126
  def eql?(other); end

  # Expanding is supported by almost all patterns (notable exceptions are {Mustermann::Shell},
  # {Mustermann::Regular} and {Mustermann::Simple}).
  #
  # Union {Mustermann::Composite} patterns (with the | operator) support expanding if all
  # patterns they are composed of also support it.
  #
  # @example Checking if a pattern supports expanding
  #   if pattern.respond_to? :expand
  #   pattern.expand(name: "foo")
  #   else
  #   warn "does not support expanding"
  #   end
  # @example Expanding a pattern
  #   pattern = Mustermann.new('/:name(.:ext)?')
  #   pattern.expand(name: 'hello')             # => "/hello"
  #   pattern.expand(name: 'hello', ext: 'png') # => "/hello.png"
  # @note This method is only implemented by certain subclasses.
  # @param behavior [Symbol] What to do with additional key/value pairs not present in the values hash.
  #   Possible options: :raise, :ignore, :append.
  # @param values [Hash{Symbol: #to_s, Array<#to_s>}] Values to use for expansion.
  # @raise [NotImplementedError] raised if expand is not supported.
  # @raise [Mustermann::ExpandError] raised if a value is missing or unknown
  # @return [String] expanded string
  # @see Mustermann::Expander
  #
  # pkg:gem/mustermann#lib/mustermann/pattern.rb:240
  def expand(behavior = T.unsafe(nil), values = T.unsafe(nil)); end

  # Used by Ruby internally for hashing.
  #
  # @return [Integer] same has value for patterns that are equal
  #
  # pkg:gem/mustermann#lib/mustermann/pattern.rb:112
  def hash; end

  # pkg:gem/mustermann#lib/mustermann/pattern.rb:366
  def inspect; end

  # @param string [String] The string to match against
  # @return [MatchData, Mustermann::SimpleMatch, nil] MatchData or similar object if the pattern matches.
  # @see Mustermann::SimpleMatch
  # @see http://ruby-doc.org/core-2.0/MatchData.html MatchData
  # @see http://ruby-doc.org/core-2.0/Regexp.html#method-i-match Regexp#match
  #
  # pkg:gem/mustermann#lib/mustermann/pattern.rb:91
  def match(string); end

  # @return [Hash{String: Array<Integer>}] capture names mapped to capture index.
  # @see http://ruby-doc.org/core-2.0/Regexp.html#method-i-named_captures Regexp#named_captures
  #
  # pkg:gem/mustermann#lib/mustermann/pattern.rb:192
  def named_captures; end

  # @return [Array<String>] capture names.
  # @see http://ruby-doc.org/core-2.0/Regexp.html#method-i-names Regexp#names
  #
  # pkg:gem/mustermann#lib/mustermann/pattern.rb:198
  def names; end

  # options hash passed to new (with unsupported options removed)
  #
  # pkg:gem/mustermann#lib/mustermann/pattern.rb:67
  def options; end

  # @param string [String] the string to match against
  # @return [Hash{String: String, Array<String>}, nil] Sinatra style params if pattern matches.
  #
  # pkg:gem/mustermann#lib/mustermann/pattern.rb:204
  def params(string = T.unsafe(nil), captures: T.unsafe(nil), offset: T.unsafe(nil)); end

  # Tries to match the pattern against the beginning of the string (as opposed to the full string).
  # Will return the substring if it matches.
  #
  # @example
  #   pattern = Mustermann.new('/:name')
  #   pattern.peek("/Frank/Sinatra") # => "/Frank"
  # @param string [String] The string to match against
  # @return [String, nil] matched subsctring
  #
  # pkg:gem/mustermann#lib/mustermann/pattern.rb:153
  def peek(string); end

  # Tries to match the pattern against the beginning of the string (as opposed to the full string).
  # Will return a MatchData or similar instance for the matched substring.
  #
  # @example
  #   pattern = Mustermann.new('/:name')
  #   pattern.peek("/Frank/Sinatra") # => #<MatchData "/Frank" name:"Frank">
  # @param string [String] The string to match against
  # @return [MatchData, Mustermann::SimpleMatch, nil] MatchData or similar object if the pattern matches.
  # @see #peek_params
  #
  # pkg:gem/mustermann#lib/mustermann/pattern.rb:168
  def peek_match(string); end

  # Tries to match the pattern against the beginning of the string (as opposed to the full string).
  # Will return a two element Array with the params parsed from the substring as first entry and the length of
  # the substring as second.
  #
  # @example
  #   pattern   = Mustermann.new('/:name')
  #   params, _ = pattern.peek_params("/Frank/Sinatra")
  #
  #   puts "Hello, #{params['name']}!" # Hello, Frank!
  # @param string [String] The string to match against
  # @return [Array<Hash, Integer>, nil] Array with params hash and length of substing if matched, nil otherwise
  #
  # pkg:gem/mustermann#lib/mustermann/pattern.rb:185
  def peek_params(string); end

  # Tries to match the pattern against the beginning of the string (as opposed to the full string).
  # Will return the count of the matching characters if it matches.
  #
  # @example
  #   pattern = Mustermann.new('/:name')
  #   pattern.size("/Frank/Sinatra") # => 6
  # @param string [String] The string to match against
  # @return [Integer, nil] the number of characters that match
  #
  # pkg:gem/mustermann#lib/mustermann/pattern.rb:139
  def peek_size(string); end

  # @return [Boolean]
  # @see Object#respond_to?
  #
  # pkg:gem/mustermann#lib/mustermann/pattern.rb:353
  def respond_to?(method, *args); end

  # pkg:gem/mustermann#lib/mustermann/pattern.rb:371
  def simple_inspect; end

  # @example
  #   pattern = Mustermann.new('/:a/:b')
  #   strings = ["foo/bar", "/foo/bar", "/foo/bar/"]
  #   strings.detect(&pattern) # => "/foo/bar"
  # @return [Proc] proc wrapping {#===}
  #
  # pkg:gem/mustermann#lib/mustermann/pattern.rb:346
  def to_proc; end

  # @return [String] the string representation of the pattern
  #
  # pkg:gem/mustermann#lib/mustermann/pattern.rb:82
  def to_s; end

  # Generates a list of URI template strings representing the pattern.
  #
  # Note that this transformation is lossy and the strings matching these
  # templates might not match the pattern (and vice versa).
  #
  # This comes in quite handy since URI templates are not made for pattern matching.
  # That way you can easily use a more precise template syntax and have it automatically
  # generate hypermedia links for you.
  #
  # Template generation is supported by almost all patterns (notable exceptions are
  # {Mustermann::Shell}, {Mustermann::Regular} and {Mustermann::Simple}).
  # Union {Mustermann::Composite} patterns (with the | operator) support template generation
  # if all patterns they are composed of also support it.
  #
  # @example Checking if a pattern supports expanding
  #   if pattern.respond_to? :to_templates
  #   pattern.to_templates
  #   else
  #   warn "does not support template generation"
  #   end
  # @example generating templates
  #   Mustermann.new("/:name").to_templates                   # => ["/{name}"]
  #   Mustermann.new("/:foo(@:bar)?/*baz").to_templates       # => ["/{foo}@{bar}/{+baz}", "/{foo}/{+baz}"]
  #   Mustermann.new("/{name}", type: :template).to_templates # => ["/{name}"]
  # @example generating templates from composite patterns
  #   pattern  = Mustermann.new('/:name')
  #   pattern |= Mustermann.new('/{name}', type: :template)
  #   pattern |= Mustermann.new('/example/*nested')
  #   pattern.to_templates # => ["/{name}", "/example/{+nested}"]
  # @note This method is only implemented by certain subclasses.
  # @raise [NotImplementedError]
  # @return [Array<String>] list of URI templates
  #
  # pkg:gem/mustermann#lib/mustermann/pattern.rb:279
  def to_templates; end

  # Returns the value of attribute uri_decode.
  #
  # pkg:gem/mustermann#lib/mustermann/pattern.rb:63
  def uri_decode; end

  # @overload &
  # @overload ^
  # @overload |
  # @param other [Mustermann::Pattern, String] the other pattern
  # @return [Mustermann::Pattern] a composite pattern
  #
  # pkg:gem/mustermann#lib/mustermann/pattern.rb:315
  def |(other); end

  private

  # pkg:gem/mustermann#lib/mustermann/pattern.rb:377
  def map_param(key, value); end

  # @return [Boolean]
  # @see #respond_to?
  #
  # pkg:gem/mustermann#lib/mustermann/pattern.rb:361
  def respond_to_special?(method); end

  # pkg:gem/mustermann#lib/mustermann/pattern.rb:382
  def unescape(string, decode = T.unsafe(nil)); end

  class << self
    # @overload new
    # @param options [Hash] options for fine-tuning the pattern behavior
    # @param string [String] the string representation of the pattern
    # @raise [ArgumentError] if some option is not supported
    # @raise [Mustermann::Error] if the pattern can't be generated from the string
    # @return [Mustermann::Pattern] a new instance of Mustermann::Pattern
    # @see #initialize
    #
    # pkg:gem/mustermann#lib/mustermann/pattern.rb:50
    def new(string, ignore_unknown_options: T.unsafe(nil), **options); end

    # Registers the pattern with Mustermann.
    #
    # @see Mustermann.register
    #
    # pkg:gem/mustermann#lib/mustermann/pattern.rb:34
    def register(*names); end

    # @param option [Symbol] The option to check.
    # @return [Boolean] Whether or not option is supported.
    #
    # pkg:gem/mustermann#lib/mustermann/pattern.rb:40
    def supported?(option, **options); end

    # List of supported options.
    #
    # @overload supported_options
    # @overload supported_options
    #
    # pkg:gem/mustermann#lib/mustermann/pattern.rb:24
    def supported_options(*list); end
  end
end

# pkg:gem/mustermann#lib/mustermann/pattern.rb:388
Mustermann::Pattern::ALWAYS_ARRAY = T.let(T.unsafe(nil), Array)

# Superclass for patterns that internally compile to a regular expression.
#
# @abstract
# @see Mustermann::Pattern
#
# pkg:gem/mustermann#lib/mustermann/regexp_based.rb:9
class Mustermann::RegexpBased < ::Mustermann::Pattern
  extend ::Forwardable

  # @param options [Hash] options for fine-tuning the pattern behavior
  # @param string [String] the string representation of the pattern
  # @return [Pattern] a new instance of Pattern
  # @see Mustermann.new
  # @see file:README.md#Types_and_Options "Types and Options" in the README
  #
  # pkg:gem/mustermann#lib/mustermann/regexp_based.rb:17
  def initialize(string, **options); end

  # pkg:gem/mustermann#lib/mustermann/regexp_based.rb:40
  def ===(*_arg0, **_arg1, &_arg2); end

  # pkg:gem/mustermann#lib/mustermann/regexp_based.rb:40
  def =~(*_arg0, **_arg1, &_arg2); end

  # pkg:gem/mustermann#lib/mustermann/regexp_based.rb:40
  def match(*_arg0, **_arg1, &_arg2); end

  # pkg:gem/mustermann#lib/mustermann/regexp_based.rb:40
  def named_captures(*_arg0, **_arg1, &_arg2); end

  # pkg:gem/mustermann#lib/mustermann/regexp_based.rb:40
  def names(*_arg0, **_arg1, &_arg2); end

  # @param string [String] The string to match against
  # @return [MatchData, Mustermann::SimpleMatch, nil] MatchData or similar object if the pattern matches.
  # @see #peek_params
  #
  # pkg:gem/mustermann#lib/mustermann/regexp_based.rb:35
  def peek_match(string); end

  # @param string [String] The string to match against
  # @return [Integer, nil] the number of characters that match
  #
  # pkg:gem/mustermann#lib/mustermann/regexp_based.rb:27
  def peek_size(string); end

  # @return [Regexp] regular expression equivalent to the pattern.
  #
  # pkg:gem/mustermann#lib/mustermann/regexp_based.rb:11
  def regexp; end

  # @return [Regexp] regular expression equivalent to the pattern.
  #
  # pkg:gem/mustermann#lib/mustermann/regexp_based.rb:12
  def to_regexp; end

  private

  # @raise [NotImplementedError]
  #
  # pkg:gem/mustermann#lib/mustermann/regexp_based.rb:42
  def compile(**options); end
end

# Fakes MatchData for patterns that do not support capturing.
#
# @see http://ruby-doc.org/core-2.0/MatchData.html MatchData
#
# pkg:gem/mustermann#lib/mustermann/simple_match.rb:5
class Mustermann::SimpleMatch
  # @api private
  # @return [SimpleMatch] a new instance of SimpleMatch
  #
  # pkg:gem/mustermann#lib/mustermann/simple_match.rb:7
  def initialize(string = T.unsafe(nil), names: T.unsafe(nil), captures: T.unsafe(nil)); end

  # pkg:gem/mustermann#lib/mustermann/simple_match.rb:38
  def +(other); end

  # @return [nil] imitates MatchData interface
  #
  # pkg:gem/mustermann#lib/mustermann/simple_match.rb:29
  def [](*args); end

  # @return [Array<String>] empty array for imitating MatchData interface
  #
  # pkg:gem/mustermann#lib/mustermann/simple_match.rb:24
  def captures; end

  # @return [String] string representation
  #
  # pkg:gem/mustermann#lib/mustermann/simple_match.rb:45
  def inspect; end

  # @return [Array<String>] empty array for imitating MatchData interface
  #
  # pkg:gem/mustermann#lib/mustermann/simple_match.rb:19
  def names; end

  # @return [String] the string that was matched against
  #
  # pkg:gem/mustermann#lib/mustermann/simple_match.rb:14
  def to_s; end
end
