# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `mustermann-grape` gem.
# Please instead update this file by running `bin/tapioca gem mustermann-grape`.


# pkg:gem/mustermann-grape#lib/mustermann/grape.rb:6
module Mustermann; end

# Grape style pattern implementation.
#
# @example
#   Mustermann.new('/:foo', type: :grape) === '/bar' # => true
# @see Mustermann::Pattern
# @see file:README.md#grape Syntax description in the README
#
# pkg:gem/mustermann-grape#lib/mustermann/grape.rb:14
class Mustermann::Grape < ::Mustermann::AST::Pattern; end

# pkg:gem/mustermann-grape#lib/mustermann/grape.rb:18
class Mustermann::Grape::Parser < ::Mustermann::AST::Parser; end
