# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Grape::DSL::Callbacks`.
# Please instead update this file by running `bin/tapioca dsl Grape::DSL::Callbacks`.


module Grape::DSL::Callbacks
  mixes_in_class_methods ::Grape::DSL::Configuration::ClassMethods
end
