# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Grape::DSL::Helpers`.
# Please instead update this file by running `bin/tapioca dsl Grape::DSL::Helpers`.


module Grape::DSL::Helpers
  mixes_in_class_methods ::Grape::DSL::Configuration::ClassMethods
end
