# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Grape::DSL::RequestResponse`.
# Please instead update this file by running `bin/tapioca dsl Grape::DSL::RequestResponse`.


module Grape::DSL::RequestResponse
  mixes_in_class_methods ::Grape::DSL::Configuration::ClassMethods
end
