# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Grape::DSL::Validations`.
# Please instead update this file by running `bin/tapioca dsl Grape::DSL::Validations`.


module Grape::DSL::Validations
  mixes_in_class_methods ::Grape::DSL::Configuration::ClassMethods
end
