name: CI

on: [push]

permissions:
  contents: read

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - uses: ruby/setup-ruby@89f90524b88a01fe6e0b732220432cc6142926af # v1.313.0
        with:
          bundler-cache: true

      - name: Run bundler-audit
        run: |
          bundle exec bundle-audit check --update

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - uses: ruby/setup-ruby@89f90524b88a01fe6e0b732220432cc6142926af # v1.313.0
        with:
          bundler-cache: true

      - name: Run Rubocop
        run: |
          bundle exec rubocop --parallel

  test:
    runs-on: ubuntu-latest

    name: Ruby ${{ matrix.ruby }}
    continue-on-error: ${{ matrix.ruby == 'head' }}
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - "3.3"
          - "3.4"
          - "4.0"
          - head

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - uses: ruby/setup-ruby@89f90524b88a01fe6e0b732220432cc6142926af # v1.313.0
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Ensure RBI files are up-to-date
        run: |
          bundle exec tapioca gems --verify

      - name: Run Sorbet
        run: bundle exec srb

      - name: Run tests
        run: bundle exec rake test
